### ISSUE TITLE
Need of a jdbc plugin for as400

### ISSUE THREAD

**Issue by Berni78** [kestra-io/plugin-jdbc#248]
### Feature description

We would like to evaluate Kestra in order to replace our current Data Pipeline solution.

IBM AS400 gives access to DB2 via JDBC driver in the form of jdbc:as400://hostname/schema …
We would need to be able to connect to DB2 from Kestra to build some of our key data pipelines.
We’ve seen that a jdbc plugin has been built for Oracle and don’t need more functionalities than this one (trigger, query, …).

It would be great if a jdbc-as400db2 could be derived from it.
We are able to list data type differences between the two RDBMS.

thanks for your help,
Bernard

**Comment by loicmathieu** [comment]
Hi,
I think the DB2 of an AS400 can be accessed using the OpenSource DB2 JDBC driver if using the DB2 protocol instead of the AS400 protocol (see this [IBM support for reference](https://www.ibm.com/support/pages/accessing-iseries-db2-as400-database-jdbc)). So by using a JDBC URL starting with `jdbc:db2:`.

**Comment by Berni78** [comment]
Hi,
Access DB2 via JDBC require an IBM Licence (at the IBM Price !!!) that we don’t have or à Cognos BI engine that we don’t need.
The Talend pipeline is actually already use the JDBC AS400 that provides the same access to DB2 (except that authentication is done at the OS level) for free.
We also use the JT400 for SQL CLI like dBeaver for exemple.
